// By Codilo (:

console.clear();

"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #3949AB;font-weight: bold;",
"color: #D32F2F;font-weight: bold;", "color: #D32F2F;font-weight: bold;";